name: Solar-system Deployment reusable workflow

on:
    workflow_call: 

jobs:
    reuse-deploy:
        environment:
          name: development
          url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        outputs: 
          APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
    
            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.34.0'
              id: install
    
            - uses: azure/k8s-set-context@v4
              with:
                 method: kubeconfig
                 kubeconfig: ${{ secrets.KUBECONFIG }} 
    
    
            - name: Fetch Kubernetes Cluster details
              run: |
                kubectl version
                echo --------------------------------
                kubectl get nodes
                kubectl get pods
    
            - name: Replace tokens in manifest file
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '__'
                tokenSuffix: '__'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS }}
                IMAGE: kloude/node-test:${{ github.sha}}
    
            - name: Show replaced files
              run: |
                cat kubernetes/development/*.yaml
    
    
            - name: Create mongodb Secret
              run: |
                kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
                --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
                --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -
    
            - name: Dev Deployment
              run: |
                kubectl apply -f  kubernetes/development
    
            - name: Set App ingress HOST Url
              id: set-ingress-host-address
              run: |
                echo "APP_INGRESS_HOST=$(kubectl get httproute solar-system-route -n default -o jsonpath='{.spec.hostnames[0]}')" >> "$GITHUB_OUTPUT"
                echo "APP_INGRESS_HOST"
    
   
